# Generated by Django 4.1.3 on 2024-01-24 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('vehicle_number', models.CharField(max_length=255)),
                ('rc_book', models.CharField(max_length=255)),
                ('rc_book_image', models.ImageField(blank=True, null=True, upload_to='rc_book_images/')),
                ('previous_policy', models.BooleanField(default=False)),
                ('previous_policy_image', models.ImageField(blank=True, null=True, upload_to='previous_policy_images/')),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PolicyIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=15)),
                ('p_number', models.CharField(max_length=255)),
                ('v_number', models.CharField(max_length=255)),
                ('Vehicle', models.CharField(max_length=255)),
                ('c_number', models.CharField(max_length=255)),
                ('e_number', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('HP_bank', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('New', 'New'), ('Data', 'Data'), ('Renewal', 'Renewal'), ('Endorsement', 'Endorsement')], default='Data', max_length=20)),
                ('insurance_type', models.CharField(choices=[('Full', 'Full'), ('TP', 'TP'), ('SOD', 'SOD'), ('Package', 'Package'), ('Health', 'Health')], default='TP', max_length=20)),
                ('insurance_portal', models.CharField(choices=[('Mintpro', 'Mintpro'), ('Agency', 'Agency'), ('Ahmedabad', 'Ahmedabad'), ('IRSS', 'IRSS'), ('Probus', 'Probus'), ('Insurance_Dekho', 'Insurance_Dekho')], default='Agency', max_length=20)),
                ('I_company', models.CharField(max_length=255)),
                ('payment', models.CharField(max_length=255)),
                ('payment_sos', models.CharField(max_length=255)),
                ('PS_date', models.DateField()),
                ('PE_date', models.DateField()),
                ('Ncb', models.IntegerField()),
                ('odNetPremium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commissionPercentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tdsPercentage', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('profit_after_tds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payout_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Executive', models.CharField(max_length=255)),
                ('DSA', models.CharField(max_length=255)),
            ],
        ),
    ]
