# Generated by Django 4.1.3 on 2024-01-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=255)),
                ('rc_book', models.CharField(max_length=255)),
                ('rc_book_image', models.ImageField(upload_to='rc_book_images/')),
                ('previous_policy', models.CharField(max_length=255)),
                ('previous_policy_image', models.ImageField(upload_to='previous_policy_images/')),
                ('end_date', models.DateField()),
                ('insurance_enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.insuranceenquiry')),
            ],
        ),
    ]
