# Generated by Django 4.1.3 on 2024-01-24 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_insuranceenquiry_vehicleinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_book', models.CharField(max_length=255)),
                ('rc_book_image', models.ImageField(upload_to='rc_book_images/')),
                ('document', models.FileField(upload_to='documents/')),
                ('loan_enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.loanenquiry')),
            ],
        ),
    ]
