# Generated by Django 5.0.1 on 2024-01-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_number_insuranceenquiry_mobile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyissue',
            options={'ordering': ['date', 'name', 'number', 'p_number', 'v_number', 'Vehicle', 'c_number', 'e_number', 'Location', 'HP_bank', 'business_type', 'insurance_type', 'insurance_portal', 'I_company', 'payment', 'payment_sos', 'PS_date', 'PE_date', 'Ncb', 'Premium', 'odNetPremium', 'commissionPercentage', 'PayoutDiscount', 'payout_discount', 'profit', 'tdsPercentage', 'profit_after_tds', 'net_profit', 'Executive', 'DSA']},
        ),
        migrations.AddField(
            model_name='policyissue',
            name='PayoutDiscount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='policyissue',
            name='Premium',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='DSA',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='Executive',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='HP_bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='I_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='Location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='Ncb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='PE_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='PS_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='Vehicle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='c_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='e_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='insurance_portal',
            field=models.CharField(blank=True, choices=[('Mintpro', 'Mintpro'), ('Agency', 'Agency'), ('Ahmedabad', 'Ahmedabad'), ('IRSS', 'IRSS'), ('Probus', 'Probus'), ('Insurance_Dekho', 'Insurance_Dekho')], default='Agency', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='p_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='payment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='payment_sos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='tdsPercentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='policyissue',
            name='v_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
