# Generated by Django 5.0.1 on 2024-01-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_policyissue_options_policyissue_payoutdiscount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyissue',
            options={},
        ),
    ]
