# Generated by Django 5.0.1 on 2024-01-31 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_policyissue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyissue',
            options={'ordering': ['date', 'name', 'number', 'p_number', 'v_number', 'Vehicle', 'c_number', 'e_number', 'Location', 'HP_bank', 'business_type', 'insurance_type', 'insurance_portal', 'I_company', 'payment', 'payment_sos', 'PS_date', 'PE_date', 'Ncb', 'Premium', 'odNetPremium', 'commissionPercentage', 'PayoutDiscount', 'payout_discount', 'profit', 'tdsPercentage', 'profit_after_tds', 'net_profit', 'Executive', 'DSA']},
        ),
    ]
