# Generated by Django 5.0.1 on 2024-02-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_policyissue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinformation',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vehicleinformation',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
