# Generated by Django 5.0.1 on 2024-02-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_policyissue_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyissue',
            options={'ordering': ['date', 'name', 'number', 'p_number', 'v_number', 'Vehicle', 'c_number', 'e_number', 'Location', 'HP_bank', 'business_type', 'insurance_type', 'insurance_portal', 'I_company', 'payment', 'payment_sos', 'PS_date', 'PE_date', 'Ncb', 'Premium', 'odNetPremium', 'commissionPercentage', 'payoutDiscount', 'PayoutAmount', 'profitResult', 'tdsPercentage', 'profitAfterTDSResult', 'netProfitResult', 'Executive', 'DSA']},
        ),
        migrations.RenameField(
            model_name='policyissue',
            old_name='PayoutDiscount',
            new_name='PayoutAmount',
        ),
        migrations.RenameField(
            model_name='policyissue',
            old_name='net_profit',
            new_name='netProfitResult',
        ),
        migrations.RenameField(
            model_name='policyissue',
            old_name='payout_discount',
            new_name='payoutDiscount',
        ),
        migrations.RenameField(
            model_name='policyissue',
            old_name='profit',
            new_name='profitAfterTDSResult',
        ),
        migrations.RenameField(
            model_name='policyissue',
            old_name='profit_after_tds',
            new_name='profitResult',
        ),
    ]
