# Generated by Django 5.0.1 on 2024-02-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_policyissue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyissue',
            name='number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
