# Generated by Django 5.0.1 on 2024-02-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_policyissue_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinformation',
            name='previous_policy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='previous_policy_image',
            field=models.ImageField(blank=True, null=True, upload_to='previous_policy_images/'),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='rc_book',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='rc_book_image',
            field=models.ImageField(blank=True, null=True, upload_to='rc_book_images/'),
        ),
    ]
