# Generated by Django 5.0.1 on 2024-02-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_vehicleinformation_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='rc_book',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='rc_book_image',
            field=models.ImageField(blank=True, upload_to='rc_book_images/'),
        ),
    ]
