# Generated by Django 5.0.1 on 2024-02-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_document_rc_book_alter_document_rc_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='rc_book',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='rc_book_image',
            field=models.ImageField(upload_to='rc_book_images/'),
        ),
    ]
