# Generated by Django 5.0.1 on 2024-02-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_document_rc_book_alter_document_rc_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='rc_book',
        ),
        migrations.RemoveField(
            model_name='document',
            name='rc_book_image',
        ),
        migrations.AddField(
            model_name='loanenquiry',
            name='rc_book',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='loanenquiry',
            name='rc_book_image',
            field=models.ImageField(blank=True, null=True, upload_to='rc_book_images/'),
        ),
        migrations.AlterField(
            model_name='loanenquiry',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loanenquiry',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
